(in-package :thierry-technologies.com/2010/01/masyaf)

(defun get-2d-game-char-rendering (game renderers)
  (let ((rendering (make-array (reverse (space-size (space game))) :element-type 'character)))
    (do-grid (point (space game))
      (let ((coords (vect-coords point)))
	(named-let rec ((renderers renderers))
	  (cif char (funcall (first renderers) game coords)
	       (setf (apply #'aref rendering (reverse coords)) char)
	       (rec (rest renderers))))))
    rendering))

(defun render-2d-spatial-game-by-char (game renderers)
  (let ((rendering (get-2d-game-char-rendering game renderers)))
    (dotimes (line (first (array-dimensions rendering)))
      (dotimes (row (second (array-dimensions rendering)))
	(princ (aref rendering line row)))
      (terpri))))
